dependencies:
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.4.0
  dhtxx:
    url: github.com/toitware/toit-dhtxx
    version: ^1.3.1
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.1.0
  mqtt:
    url: github.com/toitware/mqtt
    version: ^2.2.0
